version: "3.5"

services:
  nginx:
    depends_on:
      - wordpress
    container_name: nginx
    build: ./nginx
    networks:
      - localhost
    ports:
      - "443:443"
    volumes:
      - wp-files:/var/www/wordpress
    restart: always
  mariadb:
    container_name: mariadb
    build: ./mariadb
    networks:
      - localhost
    volumes:
      - mariadb:/var/lib/mysql
    restart: always
  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress
    build: ./wordpress
    networks:
      - localhost
    volumes:
      - wp-files:/var/www/wordpress
    restart: always

networks:
  localhost:

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/nlaurids/data/wp-db
  wp-files:
    name: wp-files
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/nlaurids/data/wp-files