services:
  nginx:
    depends_on:
      - wordpress
    container_name: nginx
    build: ./nginx
    image: nginx
    networks:
      - localhost
    ports:
      - "443:443"
    volumes:
      - type: volume
        source: wp-files
        target: /var/www/wordpress
    restart: always
  mariadb:
    container_name: mariadb
    build: ./mariadb
    image: mariadb
    networks:
      - localhost
    volumes:
      - type: volume
        source: wp-db
        target: /var/lib/mysql
    restart: always
  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress
    build: ./wordpress
    image: wordpress
    networks:
      - localhost
    volumes:
      - type: volume
        source: wp-files
        target: /var/www/wordpress
    restart: always

networks:
  localhost:

volumes:
  wp-db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/nlaurids/data/wp-db
      
  wp-files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/nlaurids/data/wp-files